version: '3.8'

services:
  postgres:
    hostname: postgres
    image: postgres
    container_name: i18n-postgres
    restart: always
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=i18n_db
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: { }

networks:
  my_network: { }