spring:
  datasource:
    url: jdbc:postgresql://${DB_CONNECTION_IP:localhost}:${DB_CONNECTION_PORT:5431}/${DB_CONNECTION_DATABASE:i18n_db}?currentSchema=${DB_CONNECTION_SCHEMA:public}
    username: ${DB_CONNECTION_USERNAME:postgres}
    password: ${DB_CONNECTION_PASSWORD:password}
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_CONNECTION_SCHEMA:public}
        temp:
          use_jdbc_metadata_defaults: false